<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Mon application ZendFramework</title>

<link rel="stylesheet" type="text/css" media="screen,projection" 
			href="<?php echo $this->baseUrl();?>/css/jquery-ui.css"/>
	<link rel="stylesheet" type="text/css" media="screen,projection" 
		href="<?php echo $this->baseUrl();?>/css/global.css"/>
	<link rel="stylesheet" type="text/css" media="screen,projection" 
		href="<?php echo $this->baseUrl();?>/js/jquery-ui/css/ui-lightness/jquery-ui-1.9.1.custom.css"/>
	<link rel="stylesheet" type="text/css" media="screen,projection" 
		href="<?php echo $this->baseUrl();?>/css/jquery-ui.css"/>
	<link rel="stylesheet" type="text/css" media="screen,projection" 
		href="<?php echo $this->baseUrl();?>/css/jquery-ui.css"/>
	<link rel="stylesheet" type="text/css" media="screen,projection" 
		href="<?php echo $this->baseUrl();?>/js/colorpicker/css/colorpicker.css"/>	
	<link rel="stylesheet" type="text/css" media="screen,projection" 
		href="<?php echo $this->baseUrl();?>/js/colorpicker/css/layout.css"/>
	
	
	<!--  pour le drag and drop tree  -->
	<link rel="stylesheet" 
			href="<?php echo $this->baseUrl();?>/tree/css/drag-drop-folder-tree.css" type="text/css"></link>
	<link rel="stylesheet" 
			href="<?php echo $this->baseUrl();?>/tree/css/context-menu.css" type="text/css"></link>
	

	
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/jquery-ui/js/jquery-1.8.2.js"></script>
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/jquery-ui/js/jquery-ui-1.9.1.custom.js"></script>
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/jquery-ui.js"></script>
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/interface.js"></script>
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/colorpicker/js/eye.js"></script>

	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/colorpicker/js/layout.js"></script>
		
			<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/colorpicker/js/colorpicker.js"></script>

	<script type="text/javascript"  
		src="<?php echo $this->baseUrl();?>/js/jfu/js/vendor/jquery.ui.widget.js"></script>
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/jfu/js/jquery.iframe-transport.js"></script>
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/js/jfu/js/jquery.fileupload.js"></script>
		
		<!--  Pour le drag and drop  -->
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tree/js/ajax.js">
	</script>
	<script type="text/javascript" 
		src="<?php echo $this->baseUrl();?>/tree/js/context-menu.js">
	</script>
	<!-- IMPORTANT! INCLUDE THE context-menu.js FILE BEFORE drag-drop-folder-tree.js -->
	<script type="text/javascript" 
			src="<?php echo $this->baseUrl();?>/tree/js/drag-drop-folder-tree.js">
	</script>
	
	<script type="text/javascript" 
			src="<?php echo $this->baseUrl();?>/js/jquery.mjs.nestedSortable.js">
	</script>
	
	

	<script type="text/javascript" 
		src="http://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyA_n5T5Qgop9y9AR5T9Q0MbF3v1mbaAG9I&sensor=true"></script>
		
		
	
		
		
</head>
<body>
	<div id='title' >  APPLICATION PASSBOOK LOGGUED </div>
	<div id='login-link' > <?php echo $this->profileLink(); ?></div>
	
	<div id="menus">
		<ul id="cssdropdown">
			<li class="headlink">
				<a href="<?php echo $this->baseUrl('/coupon/fill'); ?>">Create Coupon</a>
	 		</li>
	  		<li class="headlink">
	  		<a href="<?php echo $this->baseUrl('/campain/list'); ?>">Coupons Campain</a>	 
 			</li>
 			<li class="headlink">
	  		<a href="<?php echo $this->baseUrl('/stats/index'); ?>">Stats & analitycs</a>	 
 			</li>
 			 <li class="headlink">
	  			<a href="<?php echo $this->baseUrl('/contact/index'); ?>">My Contacts</a>	 
 			</li>
 			 <li class="headlink">
	  			<a href="<?php echo $this->baseUrl('/config/user'); ?>">Users settings</a>	 
 			</li>
 			 <li class="headlink">
	  			<a href="<?php echo $this->baseUrl('/'); ?>">Go Premium</a>	 
 			</li>
		</ul>
	</div>

	<div id="content-layout">
	<?php echo $this->layout()->content; ?>
	</div>


</body>



</html>