<?php 
if (!empty($liste_vehicule)) {
	 foreach ($liste_vehicule as $vehicule) {
		echo 'Titre : '.$vehicule['titre'].'<br />';
		echo 'Prix : '.$vehicule['prix'].'<br />';
		if ($vehicule['id_categorie'] == 1) {
			echo 'Type de vehicule : voiture<br />';
		}
		elseif ($vehicule['id_categorie'] == 2) {
			echo 'Type de véhicule : moto<br />';
		}
		else {
			echo 'Type de véhicule : scooter<br />';
		}
		
		echo 'Ajouté le  : '.date("j/m/Y", strtotime($vehicule['date_ajout'])).'<br />';
		if ($vehicule['date_modification'] != "0000-00-00") {
			echo 'Dernière modification le  : '.date("j/m/Y", strtotime($vehicule['date_modification'])).'<br />';
		}
		if ($vehicule['date_suppression'] != "0000-00-00") {
			echo 'Supprimé le  : '.date("j/m/Y", strtotime($vehicule['date_suppression'])).'<br />';
		}
		echo '<a href="'.$vehicule['id_vehicule'].'-'.str_replace(" ", "-",strtolower($vehicule['titre'])).'">Afficher les informations du véhicule</a><br />';
	}
}