<form action="<?php echo SITE_ROOT; ?>?coucou" method="get">
	<input type="hidden" name="controller" value="vehicule" /> 
	<input type="hidden" name="action" value="search" /> 
	<label for="recherche">Votre recherche</label>
	<input type="text" name="recherche" id="recherche"><br />
	<label for="annee">Année minimum</label>
	<input type="text" name="annee" id="annee"><br />
	<label for="km">Km maximum</label>
	<input type="text" name="km" id="km"><br />
	<label for="prix_min">Prix minimum</label>
	<input type="text" name="prix_min" id="prix_min"><br />
	<label for="prix_max">Prix maximum</label>
	<input type="text" name="prix_max" id="prix_max"><br />
	<label for="energie">Energie</label>
	<select name="energie" id="energie">
		<option value="" selected>Sélectionnez</option>
		<option value="diesel">Diesel</option>
		<option value="essence">Essence</option>
		<option value="electrique">Electrique</option>
	</select><br />
	<label for="type">Type de véhicule</label>
	<select name="type" id="type">
		<option value="" selected>Sélectionnez</option>
		<option value="voiture">Voiture</option>
		<option value="moto">Moto</option>
		<option value="scooter">Scooter</option>
	</select><br />
	<div id="select_voiture" style="display:none;">
		<label for="boite_vitesse">Boite de vitesse</label>
		<select name="boite_vitesse" id="boite_vitesse">
			<option value="" selected>Sélectionnez</option>
			<option value="automatique">Automatique</option>
			<option value="manuelle">Manuelle</option>
		</select><br />
		<label for="nb_places">Nombre de places</label>
		<select name="nb_places" id="nb_places">
			<option value="" selected>Sélectionnez</option>
			<option value="5">5</option>
			<option value="7">7</option>
			<option value="9">9</option>
		</select><br />
	</div>
	<div id="select_moto" style="display:none;">
		<label for="cylindree_m">Cylindrée</label>
		<select name="cylindree_moto" id="cylindree_m">
			<option value="" selected>Sélectionnez</option>
			<option value="50">50</option>
			<option value="125">125</option>
			<option value="250">250</option>
			<option value="500">500</option>
			<option value="750">750</option>
		</select><br />
	</div>
	<div id="select_scooter" style="display:none;">
		<label for="cylindree_s">Cylindrée</label>
		<select name="cylindree_scooter" id="cylindree_s">
			<option value="" selected>Sélectionnez</option>
			<option value="50">50</option>
			<option value="125">125</option>
			<option value="250">250</option>
			<option value="500">500</option>
			<option value="750">750</option>
		</select><br />
	</div>
	<input type="submit" value="Rechercher" />
</form>

<?php if (!empty($_GET['recherche'])) {
	echo "résultat de la recherche";
}
?>